name: trendit
description: "What is happening"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  
  cupertino_icons: ^1.0.2
  http: ^1.1.2

  shared_preferences: ^2.0.6
  intl: ^0.18.1
  animate_do: ^3.1.2
  email_validator: ^2.1.16
  google_fonts: ^4.0.4

  url_launcher: ^6.0.12
  flutter_mailer: ^2.0.0
  package_info: ^2.0.2
  flutter_emoji: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/flutter_logo.png
    - assets/images/trendit_icon.png